name: CICD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:          
 build_push_docker_image:
  name: Build and Push Docker Image
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build Docker Image
      run: mvn k8s:build -DskipTests -Djkube.image.name=studentimage4
    
    - name: View Docker Image
      run: docker images 

    
