name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Code Quality Analysis
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: .
          token: ${{ secrets.SONARQUBE_TOKEN }}
          scannerVersion: '4.6.2'

      - name: Build and test
        run: mvn clean test
