name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: githubprojects_firebase-springboot-studentproject
          project-name: Firebase_Springboot_studentproject
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and test
        run: mvn clean test
