name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Run Tests
        run: ./mvnw test
