name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Code Quality Analysis
        uses: SonarSource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          sonar.projectKey: "Firebase_Springboot_studentproject"
          sonar.organization: "githubprojects"
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_URL }}

      - name: Build and test
        run: mvn clean test
