name: CICD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse_code:
    name: Code Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up JDK 17
        run: |
          ls
          mkdir dockerfiles
          ls
