name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:          
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID  }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Update application YAML
        run: |
          sed -i 's/port: 8080/port: 8082/' src/main/resources/application.properties
      
      - name: Build Docker Image
        run: mvn k8s:build -DskipTests -Djkube.generator.name="gcr.io/studentdeployproject/studentsimage"
      
      - name: View Docker Image
        run: docker images 
      
      - name: Deploy to Google Cloud Run
        run: |
          gcloud container images list --project=studentdeployproject
          gcloud run deploy studentimage \
            --image gcr.io/studentdeployproject/studentsimage \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --region europe-west1 
      
